#ifndef SOFT_SEC_FINAL_COMMUNICATION_H
#define SOFT_SEC_FINAL_COMMUNICATION_H

#define IOCTL_ANTI_CHEAT_ENALBE_OBREGISTERCALLBACKS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)

namespace Communication {
    bool RegisterCallback();
} // Communication

#endif //SOFT_SEC_FINAL_COMMUNICATION_H